import = ["/Users/tv/.alacritty.local.toml", "/Users/tv/.config/alacritty/dracula.toml"]
live_config_reload = true

[window]
option_as_alt = "Both"

[colors]
draw_bold_text_with_bright_colors = false

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "SF Mono"
style = "Bold"

[font.italic]
family = "SF Mono"
style = "Regular Italic"

[font.normal]
family = "SF Mono"
style = "Regular"

[mouse]
hide_when_typing = true
